// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_BaDdAauP39SXszeRimsv9JubMTLyAuE',
    appId: '1:170868003587:web:ff2e0744f94b1574168f36',
    messagingSenderId: '170868003587',
    projectId: 'streamsync-bdc13',
    authDomain: 'streamsync-bdc13.firebaseapp.com',
    storageBucket: 'streamsync-bdc13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEVomoYkvHDAVsXGYcDkrx_-oMsJxAJe8',
    appId: '1:170868003587:android:3be274ba0e984750168f36',
    messagingSenderId: '170868003587',
    projectId: 'streamsync-bdc13',
    storageBucket: 'streamsync-bdc13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOa9Ovw3Kn7X51j64MhLaSkhL6pkLh8Lk',
    appId: '1:170868003587:ios:22e443090a313379168f36',
    messagingSenderId: '170868003587',
    projectId: 'streamsync-bdc13',
    storageBucket: 'streamsync-bdc13.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOa9Ovw3Kn7X51j64MhLaSkhL6pkLh8Lk',
    appId: '1:170868003587:ios:22e443090a313379168f36',
    messagingSenderId: '170868003587',
    projectId: 'streamsync-bdc13',
    storageBucket: 'streamsync-bdc13.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_BaDdAauP39SXszeRimsv9JubMTLyAuE',
    appId: '1:170868003587:web:13beacfe6a36514e168f36',
    messagingSenderId: '170868003587',
    projectId: 'streamsync-bdc13',
    authDomain: 'streamsync-bdc13.firebaseapp.com',
    storageBucket: 'streamsync-bdc13.firebasestorage.app',
  );
}
